name: 'entr'
version: '0.1.0'
config-version: 2

profile: 'entr'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  entr:
    +materialized: view

seeds:
  entr:
    examples:
      +enabled: false

vars:
  dim_entr_asset_models: ['int_dim_entr_asset__structured']
  dim_entr_tag_list_models: ['int_dim_entr_tag_list__structured', 'seed_entr_tag_list']
  fct_entr_time_series_models: ['int_fct_entr_time_series__structured']
